title: Olayinka Kabir Ahmed Data Analytics Portfolio
logo: ola.JPG
description:A data analyst with over three years experience working across different sectors, highly skilled in SQL,Excel and Power BI
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
